version: "3"
services:
  envoy:
    image: modelzoolive/envoy
    # build:
    #   context: .
    #   dockerfile: ./dockerfiles/envoy.Dockerfile
    ports:
    - 8080:8080
    - 80:80
    - 443:443
  go-proxy:
    image: modelzoolive/go
    # build:
    #   context: .
    #   dockerfile: ./dockerfiles/go.Dockerfile
  js-server:
    image: modelzoolive/js
    # build:
    #   context: .
    #   dockerfile: ./dockerfiles/js.Dockerfile
  mock-backend:
    image: modelzoo/mock-clipper
    build:
      context: .
      dockerfile: ./dockerfiles/python.Dockerfile
