apiVersion: v1
kind: Service
metadata:
  labels:
    container.label: envoy-service
  name: envoy-proxy-serv
spec:
  type: NodePort 
  selector:
    container: envoy-container
  ports:
  - protocol: TCP
    port: 9901
    targetPort: 9901
  - protocol: TCP
    port: 8080
    targetPort: 8080