apiVersion: v1
kind: Service
metadata:
  name: jsserverserv
spec:
  clusterIP: None
  ports:
  - name: http
    port: 5000
    targetPort: http
    protocol: TCP
  selector:
    metadata.labels.container.label: jscontainer