apiVersion: v1
kind: Service
metadata:
  name: js-server-serv
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  externalIPs:
  - 34.207.114.194
  selector:
    container: js-container
