apiVersion: v1
kind: Service
metadata:
  labels:
    container.label: go-service
  name: go-server-serv
spec:
  selector:
    container.label: go-container
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
