apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: js-server-deployment
  labels:
    container: js-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        container: js-container
    spec:
      containers:
      - name: js-server-container
        image: modelzoo/js
        ports:
        - containerPort: 5000
