apiVersion: v1
kind: Pod
metadata:
  labels:
    container: js-container
  name: js-server-pod
spec:
  containers:
  - image: modelzoo/js
    name: js-server-container
    ports:
    - containerPort: 5000
