apiVersion: v1
kind: Service
metadata:
  labels:
    container.label: js-service
  name: js-server-serv
spec:
  selector:
    container: js-container
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
